spring:
  application:
    name: poc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql.winvagrant.ilionx.cloud/swamp
    username: swamp
    password: swamp
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
