spring:
  application:
    name: poc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql.winvagrant.ilionx.cloud/swamp
    username: swamp
    password: swamp
